config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root  to: 'dashboard#index'
  devise_for :users, controllers: { sessions: 'sessions', registrations:'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :weeks,        only: :update
  resources :expenses,     only: :create

  get '/comparisons', to: 'comparisons#index'
  get '/settings', to: 'dashboard#settings'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense.rb
class Expense < ApplicationRecord

  belongs_to :week

  validates :manner, inclusion: { in: %w(restaurants groceries),
            message: "%{value} is not a valid" }
  validates :amount, presence: true

  before_create :set_spent_at #TODO: In the future we will have the user select date/time default Today

  scope :groceries, -> { where(manner: 'groceries') }
  scope :restaurants, -> { where(manner: 'restaurants') }

protected

  def set_spent_at
    self.spent_at = Time.now
  end

end

app/models/meal.rb
class Meal < ApplicationRecord
  
  belongs_to :week
  validates :manner, inclusion: { in: %w(eat_in eat_out),
            message: "%{value} is not a valid" }

  before_create :set_ate_at #TODO: In the future we will have the user select date/time default Today

  scope :ate_out, -> { where(manner: 'eat_out') }
  scope :ate_in, -> { where(manner: 'eat_in') }


protected

  def set_ate_at
    self.ate_at = Time.now
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :weeks

  CST = 'Central Time (US & Canada)'

  def find_week(next_week = false)
    week_end_time = Time.now.in_time_zone(CST).end_of_week
    week_end_time = week_end_time + 1.week if next_week
    weeks.where(end: week_end_time).first_or_create(start: week_end_time.beginning_of_week)
  end
end

app/models/week.rb
class Week < ApplicationRecord

  belongs_to :user
  has_many :meals, dependent: :destroy
  has_many :expenses, dependent: :destroy

  def pretty_time
    "#{start.strftime('%m/%d')}-#{self.end.strftime('%m/%d')}"
  end

  def total_expenditure
    expenses.map(&:amount).sum.to_f
  end

  def groceries_total
    expenses.groceries.map(&:amount).sum.to_f
  end

  def restaurants_total
    expenses.restaurants.map(&:amount).sum.to_f
  end

  def total_meals
    meals.count
  end

  def ate_in_meals
    meals.ate_in.count
  end

  def ate_out_meals
    meals.ate_out.count
  end

  def add_meal(m, free = false)
    manner = m == 'groceries' ? 'eat_in' : 'eat_out'
    meals.create(manner: manner, free: free)
  end

  def average
    average = total_expenditure / total_meals
    average.nan? || average.infinite? ? 0 : average.round(2)
  end

  def saved_money?(hypothetical_spent)
    hypothetical_spent - total_expenditure > 0 ? true : false
  end

  def savings_message(hypothetical_spent)
    difference = hypothetical_spent - total_expenditure

    if difference > 0
      "You've saved $#{difference}"
    elsif difference < 0
      "You've overspent $#{difference.abs}"
    else
      "You've spent exactly the same"
    end
  end

  def as_json(_ = nil)
    super(methods: [:average, :pretty_time, :total_expenditure, :total_meals, :ate_in_meals, :ate_out_meals, :groceries_total, :restaurants_total])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comparisons_controller.rb
class ComparisonsController < ApplicationController

  def index
    @weeks = current_user.weeks.order(end: :asc)
  end
  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    if user_signed_in?
      @week = current_user.find_week
    end
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def create
    week = params[:expenses][:next_week] == 'true' ? get_next_week : get_this_week
    week.expenses.create(expense_params)
    render json: { week: get_this_week }
  end

  protected
  def get_this_week
    current_user.find_week
  end

  def get_next_week
    current_user.find_week(true)
  end

  def expense_params
    params.require(:expenses).permit(:amount, :manner)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  respond_to :json

  def create
    resource = User.create(user_params)
    if resource.save
      sign_in :user, resource
      render json: {}, status: :ok
    else
      render json: humanize_errors(resource), status: 400
    end
  end

protected

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def humanize_errors(obj)
    obj.errors.messages.collect { |k, v| "#{k.to_s.humanize} #{v.to_sentence}"}.join
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  respond_to :json

  def create
    resource = User.find_for_database_authentication(email: params[:user][:email])
    return invalid_login_attempt unless resource

    if resource.valid_password?(params[:user][:password])
      sign_in :user, resource
      render json: {}, status: :ok
    else
      invalid_login_attempt
    end
  end

protected

  def invalid_login_attempt
    render json: "Invalid Username or Password", status: 401
  end

end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController

  before_action :load_week

  def update
    @week.add_meal(params[:manner])
    render json: { week: @week }
  end

protected

  def load_week
    @week = Week.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-32x32.png' %>" sizes="32x32">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-16x16.png' %>" sizes="16x16">
<link rel="manifest" href="<%= asset_path 'favicon/manifest.json' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#5bbad5">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#4caf50">

app/views/comparisons/index.html.slim
#graph-main
  = react_component \
    'Graph',
    weeks: @weeks

app/views/dashboard/index.html.slim
- if user_signed_in?
  = react_component \
    'MainApp',
    week: @week
    
- else
  .signup-login
    = react_component \
      'SignupLogin'

app/views/dashboard/settings.html.slim
h1 Settings

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta name="viewport" content="width=device-width, initial-scale=1.0" /
    title FoodBudgetApp
    = render 'application/favicon'
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'

    link rel="stylesheet" href="https://cdn.jsdelivr.net/chartist.js/0.10.1/chartist.min.css"
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    script src="https://cdn.jsdelivr.net/chartist.js/0.10.1/chartist.min.js"


  body
    nav.green
      .nav-wrapper
        = link_to root_path, class:'brand-logo' do 
          i.fa.fa-cutlery
          ' Fooo
        ul.right
          - if user_signed_in?
            li
              = link_to destroy_user_session_path, method: :delete do
                i.fa.fa-sign-out
        = render 'shared/hamburgermenu'
      

    .container
      = yield
    = render 'shared/footer'

app/views/shared/_footer.html.slim
.footer
  | In Development

app/views/shared/_hamburgermenu.html.slim
a herf="#" data-activates="mobile-demo" class="button-collapse" 
  i.fa.fa-bars
  
ul.right.hide-on-med-and-down
  li 
    = link_to 'Home', root_path
  li
    = link_to 'Compare week by week', comparisons_path
  li
    = link_to 'Settings', settings_path
    
ul.side-nav#mobile-demo
  li 
    = link_to 'Home', root_path
  li
    = link_to 'Compare week by week', comparisons_path
  li
    = link_to 'Settings', settings_path